### ISSUE TITLE
Implement Product Detail Page

### ISSUE THREAD

**Issue by London-Alex** [COSC481W-2021Fall/capstone-snack-attack#60]
As a user, I want to navigate to a product detail page by clicking on the product's image on the homepage so that I can see a product's details.

Acceptance Criteria

- [x] The homepage shows images for products.
- [x] The product images on the homepage redirect the user to the product's detail page when clicked.
- [x] The product detail page shows all of the product's details like title, image, description, price, category, and quantity.

Tasks

- [x] Query the database to fetch a set range of products and their details from the products table.
- [x] Create the route from the frontend to the backend query.
- [x] Display set of product images on the homepage, and make them link to the product's page.
- [x] Create a product page that displays the product's title, image, description, price, category, and quantity.
- [x] Show a warning on the product page if the item's quantity is 0.

**Comment by SuperRedTrain** [comment]
All the task are completed.
