### ISSUE TITLE
Edit The Cart Page With Quantity And Buttons

### ISSUE THREAD

**Issue by kindubadhan** [COSC481W-2021Fall/capstone-snack-attack#61]
Acceptance Criteria

- [x] Need to go on cart page check the products that selected

- [x] change the quantity

- [x] features to add buttons like remove item

Task

- [x] Display cart items on the cart page by clicking on cart. Show a message if the cart is empty. (kulwinder, ke)
- [x] Change the quantity by + and - button. The + button is disable if the quantity equals to the instock number of the product. The - button is disable if the quantity is 1. (kulwinder, ke)
- [x] Add a button Remove Item. (kulwinder, ke)
- [x] Add a button Proceed to checkout. (kulwinder)

**Comment by SuperRedTrain** [comment]
All task are completed.
